// web_embedding/cra-flutter/src/App/App.tsx
import React, { useRef } from 'react'
import { styled, useTheme } from '@mui/material/styles'
import AppBar from '@mui/material/AppBar'
import Box from '@mui/material/Box'
import Toolbar from '@mui/material/Toolbar'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import IconButton from '@mui/material/IconButton'
import MenuIcon from '@mui/icons-material/Menu'
import FlutterDashIcon from '@mui/icons-material/FlutterDash'
import Drawer from '@mui/material/Drawer'
import CssBaseline from '@mui/material/CssBaseline'
import List from '@mui/material/List'
import FormControl from '@mui/material/FormControl'
import MenuItem from '@mui/material/MenuItem'
import InputLabel from '@mui/material/InputLabel'
import Select, { SelectChangeEvent } from '@mui/material/Select'
import TextField from '@mui/material/TextField'
import { FlutterView } from './FlutterView/FlutterView'

const drawerWidth = 300

const Main = styled('main', { shouldForwardProp: (prop) => prop !== 'open' })<{
  open?: boolean;
}>(({ theme, open }) => ({
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  flexGrow: 1,
  transition: theme.transitions.create('margin', {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.leavingScreen,
  }),
  marginLeft: `-${drawerWidth}px`,
  ...(open && {
    transition: theme.transitions.create('margin', {
      easing: theme.transitions.easing.easeOut,
      duration: theme.transitions.duration.enteringScreen,
    }),
    marginLeft: 0,
  }),
}))

const DrawerHeader = styled('div')(({ theme }) => ({
  display: 'flex',
  alignItems: 'center',
  padding: theme.spacing(0, 1),
  // necessary for content to be below app bar
  ...theme.mixins.toolbar,
  justifyContent: 'flex-end',
}))

const FlutterAppWrapper = styled('div')(({ theme }) => ({
  border: '1px solid #eee',
  borderRadius: '5px',
  height: '480px',
  width: '320px',
  transition: theme.transitions.create('all', {
    easing: theme.transitions.easing.easeInOut,
    duration: theme.transitions.duration.enteringScreen,
  }),
  overflow: 'hidden',
}))

const EffectButton = ({ title, toggleClassName }: { title: string, toggleClassName: (name: string) => void }) => {
  const onClick = () => {
    toggleClassName(`fx-${title.toLowerCase()}`)
  }
  return (
    <Button
      variant="outlined"
      onClick={onClick}
      sx={{ minWidth: '130px' }}
    >
      {title}
    </Button>
  )
}

function App () {
  const theme = useTheme()
  const [drawerOpened, setDrawerOpened] = React.useState(false)
  const [classNames, setClassNames] = React.useState('')
  const [screen, setScreen] = React.useState('counter')
  const [clicks, setClicks] = React.useState(0)
  const [text, setText] = React.useState('')
  const flutterState = useRef<any>(null)
  const handleDrawer = () => {
    setDrawerOpened(!drawerOpened)
  }
  const onFlutterAppLoaded = (state: any) => {
    flutterState.current = state
    state.onClicksChanged(() => { setClicks(flutterState.current?.getClicks()) })
    state.onTextChanged(() => { setText(flutterState.current?.getText()) })
    state.onScreenChanged(() => { setScreen(flutterState.current?.getScreen()) })
  }
  const toggleClassName = (className: string) => {
    const classNamesArray = classNames.trim().split(/\s+/)
    const index = classNamesArray.indexOf(className)
    if (index === -1) {
      classNamesArray.push(className)
    } else {
      classNamesArray.splice(index, 1)
    }
    setClassNames(classNamesArray.join(' '))
  }
  const handleScreenChange = (event: SelectChangeEvent) => {
    flutterState.current?.setScreen(event.target.value as string)
  }
  const handleClicksChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const clicks = parseInt(event.target.value, 10) || 0
    flutterState.current?.setClicks(clicks)
  }
  const handleTextChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const text = event.target.value || ''
    flutterState.current?.setText(text)
  }
  return (
    <Box sx={{ display: 'flex', flexGrow: 1 }}>
      <CssBaseline/>
      <AppBar position="fixed" sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}>
        <Toolbar>
          <IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="menu"
            onClick={handleDrawer}
            sx={{ mr: 2 }}
          >
            <MenuIcon/>
          </IconButton>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            React 🤝 Flutter
          </Typography>
          <FlutterDashIcon/>
        </Toolbar>
      </AppBar>
      <Drawer
        open={drawerOpened}
        variant="persistent"
        anchor="left"
        sx={{
          width: drawerWidth,
          flexShrink: 0,
          [`& .MuiDrawer-paper`]: { width: drawerWidth, boxSizing: 'border-box' },
        }}
      >
        <DrawerHeader/>
        <Box sx={{ overflow: 'auto', padding: theme.spacing(1), }}>
          <List>
            <Box>
              <Typography variant="h5" component="h2">Effects</Typography>
              <Box sx={{ display: 'flex', flexGrow: 1, flexWrap: 'wrap', gap: '5px' }}>
                <EffectButton toggleClassName={toggleClassName} title="Shadow"/>
                <EffectButton toggleClassName={toggleClassName} title="Mirror"/>
                <EffectButton toggleClassName={toggleClassName} title="Resize"/>
                <EffectButton toggleClassName={toggleClassName} title="Spin"/>
              </Box>
            </Box>
            <Box mt={2}>
              <Typography variant="h5" component="h2">JS Interop</Typography>
              <FormControl fullWidth>
                <InputLabel id="screen-select-label">Screen</InputLabel>
                <Select
                  labelId="screen-select-label"
                  value={screen}
                  label="Screen"
                  onChange={handleScreenChange}
                >
                  <MenuItem value="counter">Counter</MenuItem>
                  <MenuItem value="text">TextField</MenuItem>
                  <MenuItem value="dash">Custom App</MenuItem>
                </Select>
                {screen === 'counter' && (
                  <TextField
                    label="Clicks"
                    type="number"
                    value={clicks}
                    onChange={handleClicksChange}
                    InputLabelProps={{
                      shrink: true,
                    }}
                    margin="dense"
                  />
                )}
                {screen !== 'counter' && (
                  <TextField
                    label="Text"
                    type="text"
                    value={text}
                    onChange={handleTextChange}
                    InputLabelProps={{
                      shrink: true,
                    }}
                    margin="dense"
                  />
                )}
              </FormControl>
            </Box>
          </List>
        </Box>
      </Drawer>
      <Main open={drawerOpened}>
        <FlutterAppWrapper className={classNames}>
          <FlutterView
            assetBase={process.env.PUBLIC_URL + '/flutter/'}
            src={process.env.PUBLIC_URL + '/flutter/main.dart.js'}
            appLoaded={onFlutterAppLoaded}
          />
        </FlutterAppWrapper>
      </Main>
    </Box>
  )
}

export default App

// web_embedding/ng-flutter/src/app/app.component.ts
import { ChangeDetectorRef, Component } from '@angular/core';
import { NgFlutterComponent } from './ng-flutter/ng-flutter.component';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { MatSidenavModule } from '@angular/material/sidenav';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { MatCardModule } from '@angular/material/card';
import { MatSliderModule } from '@angular/material/slider';
import { MatButtonModule } from '@angular/material/button';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';

@Component({
  standalone: true,
  selector: 'app-root',
  template: `
<mat-toolbar color="primary">
  <button
    aria-label="Toggle sidenav"
    mat-icon-button
    (click)="drawer.toggle()">
    <mat-icon aria-label="Side nav toggle icon">menu</mat-icon>
  </button>
  <span>Angular 🤝 Flutter</span>
  <span class="toolbar-spacer"></span>
  <mat-icon aria-hidden="true">flutter_dash</mat-icon>
</mat-toolbar>
<mat-sidenav-container [hasBackdrop]=false class="sidenav-container">
  <mat-sidenav #drawer mode="side" [opened]=false class="sidenav">
    <mat-nav-list autosize>
      <section>
        <h2>Effects</h2>
        <div class="button-list">
          <button class="mb-control" mat-stroked-button color="primary"
              (click)="container.classList.toggle('fx-shadow')">Shadow</button>
          <button class="mb-control" mat-stroked-button color="primary"
              (click)="container.classList.toggle('fx-mirror')">Mirror</button>
          <button class="mb-control" mat-stroked-button color="primary"
              (click)="container.classList.toggle('fx-resize')">Resize</button>
          <button class="mb-control" mat-stroked-button color="primary"
              (click)="container.classList.toggle('fx-spin')">Spin</button>
        </div>
      </section>

      <section>
        <h2>JS Interop</h2>
        <mat-form-field appearance="outline">
          <mat-label>Screen</mat-label>
          <mat-select 
              (valueChange)="this.flutterState?.setScreen($event)" 
              [value]="this.flutterState?.getScreen()">
            <mat-option value="counter">Counter</mat-option>
            <mat-option value="text">TextField</mat-option>
            <mat-option value="dash">Custom App</mat-option>
          </mat-select>
        </mat-form-field>
        @if (this.flutterState?.getScreen() === 'counter') {
          <mat-form-field appearance="outline">
            <mat-label>Clicks</mat-label>
            <input type="number" matInput (input)="onCounterSet($event)" [value]="this.flutterState?.getClicks()" />
          </mat-form-field>
        } @else {
          <mat-form-field appearance="outline">
            <mat-label>Text</mat-label>
            <input type="text" matInput (input)="onTextSet($event)" [value]="this.flutterState?.getText()" />
            @if (this.flutterState?.getText()) {
              <button matSuffix mat-icon-button aria-label="Clear" (click)="this.flutterState?.setText('')">
                <mat-icon>close</mat-icon>
              </button>
            }
          </mat-form-field>    
        }
      </section>
    </mat-nav-list>
  </mat-sidenav>

  <mat-sidenav-content class="sidenav-content">
    <div class="flutter-app" #container>
      <ng-flutter
        src="flutter/main.dart.js"
        assetBase="/flutter/"
        (appLoaded)="onFlutterAppLoaded($event)"></ng-flutter>
    </div>
  </mat-sidenav-content>
</mat-sidenav-container>
`,
  styles: [`
  :host{
    display: flex;
    height: 100%;
    flex-direction: column;
  }
  .toolbar-spacer {
    flex: 1 1 auto;
  }
  .sidenav-container {
    flex: 1;
  }
  .sidenav {
    width: 300px;
    padding: 10px;
  }
  .button-list {
    display: flex;
    flex-wrap: wrap;
    gap: 5px;
    margin-bottom: 20px;
  }
  .button-list button {
    min-width: 130px;
  }
  .sidenav-content {
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .flutter-app {
    border: 1px solid #eee;
    border-radius: 5px;
    height: 480px;
    width: 320px;
    transition: all 150ms ease-in-out;
    overflow: hidden;
  }
  `],
  imports: [
    NgFlutterComponent,
    MatToolbarModule,
    MatSidenavModule,
    MatSidenavModule,
    MatIconModule,
    CommonModule,
    MatListModule,
    MatCardModule,
    MatSliderModule,
    MatButtonModule,
    MatFormFieldModule,
    MatSelectModule,
    MatInputModule,
  ],
})
export class AppComponent {
  title = 'ng-flutter';
  flutterState?: any;

  constructor(private changeDetectorRef: ChangeDetectorRef, private breakpointObserver: BreakpointObserver) { }

  onFlutterAppLoaded(state: any) {
    this.flutterState = state;
    this.flutterState.onClicksChanged(() => { this.onCounterChanged() });
    this.flutterState.onTextChanged(() => { this.onTextChanged() });
  }

  onCounterSet(event: Event) {
    let clicks = parseInt((event.target as HTMLInputElement).value, 10) || 0;
    this.flutterState.setClicks(clicks);
  }

  onTextSet(event: Event) {
    this.flutterState.setText((event.target as HTMLInputElement).value || '');
  }

  // I need to force a change detection here. When clicking on the "Decrement"
  // button, everything works fine, but clicking on Flutter doesn't trigger a
  // repaint (even though this method is called)
  onCounterChanged() {
    this.changeDetectorRef.detectChanges();
  }

  onTextChanged() {
    this.changeDetectorRef.detectChanges();
  }
}
